# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
version: '3.3'
volumes:
  metricbeat:
services:
  mongo1:
    image: mongo:4.4@sha256:ce3d0eade688a2299e9e20454efc561a6fc8de1cbde5abb0f50feadfe758037b
    restart: unless-stopped

  redis:
    image: redis:5@sha256:fc5ecd863862f89f04334b7cbb57e93c9790478ea8188a49f6e57b0967d38c75
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18@sha256:ed43613fe3c372e98e883f36fab2597ea63c86ff8bb22b2a298d1cd4fb436bab
    restart: unless-stopped
    environment:
      - discovery.type=single-node

  influxdb:
    image: influxdb:1.8.10@sha256:0752b8858dbdc1812aa98dfd5c1856b188809af9990dab6c24383897119fb328
    restart: unless-stopped

  hearth:
    image: opencrvs/hearth:1.1.0@sha256:12892d665c395d9022eb322f713e92a0cec1e315641fe05eb1470d6dafc42148
    environment:
      - mongodb__url=mongodb://mongo1/hearth-dev
      - logger__level=warn
      - authentication__type=disabled
      - idGenerator=uuidv4
      - server__fhirVersion=stu3
    depends_on:
      - mongo1
    restart: unless-stopped

  openhim-core:
    image: jembi/openhim-core:7@sha256:863e3d868923a7972c44b6812fdb830ef5ea9b64f35c9392bb506c69ffab249e
    environment:
      - mongo_url=mongodb://mongo1/openhim-dev
      - mongo_atnaUrl=mongodb://mongo1/openhim-dev
      - logger_level=error
      - router_timeout=180000
    depends_on:
      - mongo1
    restart: unless-stopped

  openhim-console:
    image: jembi/openhim-console:1.13@sha256:caf4aef23c3702aaf9375b3a00c5d5c3f0854c15c238f2ea98cd57f9fb9f9ab6
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:RELEASE.2023-09-16T01-01-47Z.fips@sha256:013e82e0030c9ce8d41f9cffaf91a5514f3dc41aa0942ea58cf3f4e35798f2cf
    restart: unless-stopped
