title: 'Installation'
body:
  - type: markdown
    attributes:
      value: |
        ## Explain the issue & help you require

        ## What git branch are you on in Core?

        ## What git branch are you on in Countryconfig?

        If we are unable to help you here we can offer dedicated support.
        Email us at team@opencrvs.org and please answer the following questions:

        Please tell us your full name and how you wish to be referred to.
        Please tell us the name of the organisation or company you work for.
        Are you working with a government on an active country implementation? If so, ...
        Which country’s implementation are you working on?
        Tell us about your project, brief, the client and timeline if you can?
  - type: input
    id: core-version
    attributes:
      label: OpenCRVS Core version
      description: e.g 1.4.1
    validations:
      required: true
  - type: input
    id: countryconfig-version
    attributes:
      label: OpenCRVS Countryconfig version
      description: e.g 1.4.1
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Your operating system and version
      description: e.g Ubuntu 22.04
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Your node version
      description: e.g v16.20.0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Which of these describes your project best?
      options:
        - label: Testing OpenCRVS for business development, educational purposes or for personal interest.
        - label: A research project to evaluate, configure and test OpenCRVS as a possible solution for a government, an active brief or proposal.
        - label: Actively installing and configuring OpenCRVS Core for production use in a country.
        - label: Customising OpenCRVS Core code in production in a country
    validations:
      required: true
